runtime: nodejs16
instance_class: F2
env_variables:
  DATABASE_URL: "mysql://5zt616un1ebbiudtyifa:pscale_pw_PNzoo72bX6HrgTsH5NpV239DnaH97IL8XV26ws0i6wM@ap-southeast.connect.psdb.cloud/main?sslaccept:strict"
  PORT: 5000
  JWT_SECRET: "supersecret"
  JWT_REFRESH_SECRET: "supersecretrefresh"
  COOKIE_SECRET: "cookiesecret"
  REDIS_HOST: "redis-15316.c302.asia-northeast1-1.gce.cloud.redislabs.com"
  REDIS_PORT: 15316
  REDIS_PASSWORD: "3uSDhinhxzotdtKDaQHZbgmEVVqTYyGA"
  CACHE_TTL: 1800
  SMTP_HOST: "smtp-relay.sendinblue.com"
  SMTP_PORT: 587
  SMTP_EMAIL: "peerpussies@gmail.com"
  SMTP_PASSWORD: "KLkWtn7gZwchHa64"
  SMTP_NAME: "PeerPussies"
  FRONTEND_URL: "http://localhost:3000"
