version: "3.8"
services:
  dev-db:
    image: postgres:14
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - cs3219
  test-db:
    image: postgres:14
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest
    networks:
      - cs3219
  dev-redis:
    image: "redis:7.0-alpine"
    ports:
      - 6380:6379
    networks:
        - cs3219
  test-redis:
    image: "redis:7.0-alpine"
    ports:
      - 6381:6379
    networks:
        - cs3219
networks:
  cs3219:
