version: "3.8"
services:
  dev-db:
    image: mysql:8.0
    ports:
      - 3366:3306
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cs3219
  test-db:
    image: mysql:8.0
    ports:
      - 3367:3306
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cs3219
networks:
  cs3219:
