const QUESTION_SUMMARIES_FORMATTED = "summaries_formatted";
const QUESTION_SUMMARIES = "summaries";
const QUESTION_CONTENT = "contents";
const QUESTION_TOPICS = "topics";
const QUESTION_QOTD_CONTENT = "question_of_the_day_content";
const QUESTION_QOTD_SUMMARY = "question_of_the_day_summary";
const QUESTION_SUMMARY_DIFFICULTIES = "QUESTION_SUMMARY_DIFFICULTIES";

export {
  QUESTION_SUMMARIES,
  QUESTION_CONTENT,
  QUESTION_TOPICS,
  QUESTION_QOTD_CONTENT,
  QUESTION_QOTD_SUMMARY,
  QUESTION_SUMMARY_DIFFICULTIES,
  QUESTION_SUMMARIES_FORMATTED,
};
