import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Head from "next/head";
import Auth from "../components/auth";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div
          className="container bg-red-500"
          style={{ padding: "50px 0 100px 0" }}
        >
          <Auth />
          {/* {!session ? (
            <Auth />
          ) : (
            <Account key={session.user.id} session={session} />
          )} */}
        </div>
        {/* Connected status: {isConnected ? "Connected" : "Disconnected"} */}
      </div>
    </>
  );
};

export default Home;
