version: "3.8"
services:
  dev-db:
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: question-service
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cs3219
networks:
  cs3219:
