name: Manual CD to DO Droplet

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

jobs:
  on-merged-pr:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and run backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd g42
            git pull
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 16
            cd backend
            yarn gh:deploy >> /dev/null 2>&1 &
